language: php
php: 7.4
services:
  - docker
  - mysql
before_install:
  - composer install
  - mysql -e 'CREATE DATABASE pyp_test;'
  - php bin/console doctrine:migrations:migrate --no-interaction
script:
  - vendor/bin/phpunit