# Note that this Docker Compose is used for local development only

version: '3'

services:
  frontend:
    build: ./frontend
    ports:
      - "80"
    volumes:
      - ./frontend:/var/www/html
    working_dir: /var/www/html/public
    networks:
      - frontend
      - api_net

  frontend_db:
    image: mariadb:${MARIADB_VERSION:-11.2.2}
    environment:
      # You should definitely change the password in production
      MARIADB_ROOT_PASSWORD: ${MARIADB_PASSWORD:-!ChangeMe!}
      MARIADB_USER: pyp
      MARIADB_DATABASE: pyp
    volumes:
      - frontend_db_data:/var/lib/mysql
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
    networks:
      - frontend

  user_microservice:
    build: ./user_microservice
    ports:
      - "80"
    volumes:
      - ./user_microservice:/var/www/html
    working_dir: /var/www/html/public
    networks:
      - user_microservice
      - api_net

  user_microservice_db:
    image: mariadb:${MARIADB_VERSION:-11.2.2}
    environment:
      # You should definitely change the password in production
      MARIADB_ROOT_PASSWORD: ${MARIADB_PASSWORD:-!ChangeMe!}
      MARIADB_USER: pyp
      MARIADB_DATABASE: pyp
    volumes:
      - user_microservice_db_data:/var/lib/mysql
    networks:
      - user_microservice

volumes:
###> doctrine/doctrine-bundle ###
  frontend_db_data: {}
  user_microservice_db_data: {}
###< doctrine/doctrine-bundle ###

networks:
  api_net:
  frontend:
  user_microservice: