# Note that this Docker Compose is used for local development only

version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    image: mariadb:${MARIADB_VERSION:-11.2.2}
    environment:
      # You should definitely change the password in production
      MARIADB_ROOT_PASSWORD: ${MARIADB_PASSWORD:-!ChangeMe!}
      MARIADB_USER: pyp
      MARIADB_DATABASE: pyp
    volumes:
      - database_data:/var/lib/mysql
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

  webapp:
    build: .
    ports:
      - "80"
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html/public

volumes:
###> doctrine/doctrine-bundle ###
  database_data: {}
###< doctrine/doctrine-bundle ###
