version: '3.1'
services:
  db:
    image: mariadb:10.3.8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pyp_test
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306