name: CI
on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v0.1.4
        env:
          SSH_PASSWORD: ${{secrets.SSH_PASSWORD}}
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USERNAME}}
          password: ${{secrets.SSH_PASSWORD}}

          script: |
            cd /var/www
            echo $SSH_PASSWORD | sudo -S git clone https://github.com/dayallnash/pyp.git pyp_new
            cd pyp_new
            /usr/bin/php7.4 /usr/local/bin/composer install --no-dev
            cd ..
            echo $SSH_PASSWORD | sudo -S chmod -R 775 pyp_new
            echo $SSH_PASSWORD | sudo -S chown -R www-data:www-data pyp_new
            echo $SSH_PASSWORD | sudo -S  mv /var/www/pyp /var/www/pyp_old
            echo $SSH_PASSWORD | sudo -S  mv /var/www/pyp_new /var/www/pyp
            echo $SSH_PASSWORD | sudo -S  rm -rf /var/www/pyp_old